// <auto-generated />
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VenomPizzaMenuService.src.context;

#nullable disable

namespace VenomPizzaMenuService.Migrations
{
    [DbContext(typeof(ProductsDbContext))]
    [Migration("20250824151611_9")]
    partial class _9
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VenomPizzaMenuService.src.model.ComboProduct", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("ComboId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("ProductId", "ComboId");

                    b.HasIndex("ComboId");

                    b.ToTable("ComboProducts");
                });

            modelBuilder.Entity("VenomPizzaMenuService.src.model.PriceVariant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DishId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DishId");

                    b.ToTable("PriceVariant");
                });

            modelBuilder.Entity("VenomPizzaMenuService.src.model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Available")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<List<string>>("Categories")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("VenomPizzaMenuService.src.model.Combo", b =>
                {
                    b.HasBaseType("VenomPizzaMenuService.src.model.Product");

                    b.ToTable("Combos");
                });

            modelBuilder.Entity("VenomPizzaMenuService.src.model.Dish", b =>
                {
                    b.HasBaseType("VenomPizzaMenuService.src.model.Product");

                    b.PrimitiveCollection<List<string>>("Allergens")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<float>("Calorific")
                        .HasColumnType("real");

                    b.Property<float>("Carbohydrates")
                        .HasColumnType("real");

                    b.Property<float>("Fats")
                        .HasColumnType("real");

                    b.PrimitiveCollection<List<string>>("Ingredients")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<float>("Proteins")
                        .HasColumnType("real");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.ToTable("Dishes");
                });

            modelBuilder.Entity("VenomPizzaMenuService.src.model.ComboProduct", b =>
                {
                    b.HasOne("VenomPizzaMenuService.src.model.Combo", "Combo")
                        .WithMany("Products")
                        .HasForeignKey("ComboId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VenomPizzaMenuService.src.model.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Combo");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("VenomPizzaMenuService.src.model.PriceVariant", b =>
                {
                    b.HasOne("VenomPizzaMenuService.src.model.Dish", "Dish")
                        .WithMany("PriceVariants")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dish");
                });

            modelBuilder.Entity("VenomPizzaMenuService.src.model.Combo", b =>
                {
                    b.HasOne("VenomPizzaMenuService.src.model.Product", null)
                        .WithOne()
                        .HasForeignKey("VenomPizzaMenuService.src.model.Combo", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VenomPizzaMenuService.src.model.Dish", b =>
                {
                    b.HasOne("VenomPizzaMenuService.src.model.Product", null)
                        .WithOne()
                        .HasForeignKey("VenomPizzaMenuService.src.model.Dish", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VenomPizzaMenuService.src.model.Combo", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("VenomPizzaMenuService.src.model.Dish", b =>
                {
                    b.Navigation("PriceVariants");
                });
#pragma warning restore 612, 618
        }
    }
}
