// <auto-generated />
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VenomPizzaMenuService.src.context;

#nullable disable

namespace VenomPizzaMenuService.Migrations
{
    [DbContext(typeof(ProductsDbContext))]
    partial class ProductsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VenomPizzaMenuService.src.model.ComboProduct", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<int>("ComboId")
                        .HasColumnType("integer")
                        .HasColumnName("combo_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("ProductId", "ComboId");

                    b.HasIndex("ComboId");

                    b.ToTable("combo_products");
                });

            modelBuilder.Entity("VenomPizzaMenuService.src.model.PriceVariant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("size");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("price_variants");
                });

            modelBuilder.Entity("VenomPizzaMenuService.src.model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<List<string>>("Categories")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("categories");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_available");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("products");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("VenomPizzaMenuService.src.model.Combo", b =>
                {
                    b.HasBaseType("VenomPizzaMenuService.src.model.Product");

                    b.ToTable("combos");
                });

            modelBuilder.Entity("VenomPizzaMenuService.src.model.Dish", b =>
                {
                    b.HasBaseType("VenomPizzaMenuService.src.model.Product");

                    b.PrimitiveCollection<List<string>>("Allergens")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("allergens");

                    b.Property<float>("Calorific")
                        .HasColumnType("real")
                        .HasColumnName("calorific");

                    b.Property<float>("Carbohydrates")
                        .HasColumnType("real")
                        .HasColumnName("carbohydrates");

                    b.Property<float>("Fats")
                        .HasColumnType("real")
                        .HasColumnName("fats");

                    b.PrimitiveCollection<List<string>>("Ingredients")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("ingridients");

                    b.Property<float>("Proteins")
                        .HasColumnType("real")
                        .HasColumnName("proteins");

                    b.Property<string>("Unit")
                        .HasColumnType("text")
                        .HasColumnName("unit");

                    b.ToTable("dishes");
                });

            modelBuilder.Entity("VenomPizzaMenuService.src.model.ComboProduct", b =>
                {
                    b.HasOne("VenomPizzaMenuService.src.model.Combo", "Combo")
                        .WithMany("Products")
                        .HasForeignKey("ComboId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VenomPizzaMenuService.src.model.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Combo");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("VenomPizzaMenuService.src.model.PriceVariant", b =>
                {
                    b.HasOne("VenomPizzaMenuService.src.model.Product", "Product")
                        .WithMany("PriceVariants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("VenomPizzaMenuService.src.model.Combo", b =>
                {
                    b.HasOne("VenomPizzaMenuService.src.model.Product", null)
                        .WithOne()
                        .HasForeignKey("VenomPizzaMenuService.src.model.Combo", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VenomPizzaMenuService.src.model.Dish", b =>
                {
                    b.HasOne("VenomPizzaMenuService.src.model.Product", null)
                        .WithOne()
                        .HasForeignKey("VenomPizzaMenuService.src.model.Dish", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VenomPizzaMenuService.src.model.Product", b =>
                {
                    b.Navigation("PriceVariants");
                });

            modelBuilder.Entity("VenomPizzaMenuService.src.model.Combo", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
